### ISSUE TITLE
Upgrade to ruby 1.9.3

### ISSUE THREAD

**Issue by lizconlan** [mysociety/foi-register#229]

**Comment by garethrees** [comment]
Meh, https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

> # Support for Ruby version 1.9.3 will end on February 23, 2015

> Today we are announcing our plans for the future of Ruby version 1.9.3.

> Currently this branch is in maintenance mode, and will remain so until February 23, 2014.

> After February 23 2014, we will only provide security fixes for 1.9.3 until February 23 2015, after which all support will end for 1.9.3.

> We highly recommend that you upgrade to Ruby 2.1 or 2.0.0 as soon as possible.

**Comment by dracos** [comment]
Though 1.9.3 is the default on Ubuntu trusty, and so should theoretically be supported by them until April 2019.

**Comment by garethrees** [comment]
> Though 1.9.3 is the default on Ubuntu trusty, and so should theoretically be supported by them until April 2019.

In terms of security patches yes, but community support will swiftly drop off, so people will start abandoning 1.9.3 for libraries etc. Rails 5 will require Ruby 2.

**Comment by dracos** [comment]
Sure, though that doesn't make the existing libraries disappear :) And if it's straightforward and helps with e.g. https://github.com/mysociety/foi-register/issues/227 after all.
“Rails 5.0 is in most likelihood going to target Ruby 2.2.” and that isn't even in sid, hohum!
