### ISSUE TITLE
Send email templates to Adam so he can review signatures

### ISSUE THREAD

**Issue by mikejamesthompson** [mysociety/foi-register#236]
Perhaps we could send him the links to each one in GitHub to make things a bit simpler.

**Comment by stevenday** [comment]
I think the relevant folders in Github are:
- https://github.com/mysociety/foi-register/tree/master/app/views/request_mailer
- https://github.com/mysociety/foi-register/tree/master/app/views/response_mailer

They're in ERB syntax, but I've had a quick look through and I don't think there's anything particularly confusing in there, so should be fine to send him.

**Comment by stevenday** [comment]
I've now sent these links to him, so closing this issue.
