### ISSUE TITLE
Old requests haven't been sent to Alaveteli because they failed validation

### ISSUE THREAD

**Issue by stevenday** [mysociety/foi-register#248]
There are approximately 80 requests which haven't been synced with WDTK because they don't pass validation there. This is linked to #246. These are causing the health check to fail.

I propose that there's not a lot we can do about these, so we'll just have to adapt the health check to ignore these, once we fix #246 so that it can't happen in the future.

**Comment by lizconlan** [comment]
ticket #253 created so that we don't lose the failed requests once we stop reporting on them
