### ISSUE TITLE
Admin interface does not clearly show when a requestor has asked for their name to be withheld

### ISSUE THREAD

**Issue by lizconlan** [mysociety/foi-register#262]
Publishing of names is presented to the requester as opt-in, the admin interface should clearly show the requester's choice when responding to a request

**Comment by garethrees** [comment]
Here's the current state:

![foi-reg-show-my-name](https://cloud.githubusercontent.com/assets/282788/8650842/6ddb8680-296d-11e5-93b4-944a62d3c70e.png)

**Comment by zarino** [comment]
> Do we have an option for name and message both private? (I suspect not)

We do not.
