### ISSUE TITLE
Turn off sending of anonymous reports

### ISSUE THREAD

**Issue by stevenday** [mysociety/foi-register#263]
Brighton aren't always respecting the wishes of anonymous requestors (not least because it's hard to see when they are anonymous - #262), so it's best that we stop syncing these requests and any responses that come through Brighton's site for the time being.

This requires:
- [ ] A new setting `SYNC_ANONYMOUS_REQUESTS`
- [ ] Code to check this setting when syncing requests
- [ ] Code to check this setting when syncing responses
- [ ] #261 - so that we can mark the requests/responses we've skipped because of this setting in the db for future logic
- [ ] Updating the "has this request come from alaveteli" and "has this response come from alaveteli" logic so that it's aware of requests we might have skipped on purpose.
- [ ] Updating the health checks to ignore these skipped requests and responses
- [ ] Updating the syncing code to ignore these skipped requests in the future too (I guess?)

@lizconlan - does that cover everything?

**Comment by lizconlan** [comment]
@stevenday I think so, I'm assuming that we don't need to do anything special with responses to requests which have already beeb hidden on WDTK?

**Comment by stevenday** [comment]
@lizconlan: I guess not - if they're anonymous they'll not be sent any more, and otherwise, the functionality won't have changed from what happens now

**Comment by stevenday** [comment]
We're going to do something slightly different now, in that we're going to turn off sending of *all* reports that originate on Brighton's site, but keep syncing responses from Alavateli (and pushing new responses to those requests back). Therefore I'll close this in favour of a new ticket.
