### ISSUE TITLE
Make it more explicit that request title and body will be published on /this/ site and wdtk.com

### ISSUE THREAD

**Issue by BenJam** [mysociety/foi-register#264]
The current new request page

https://foi.brighton-hove.gov.uk/requests/new

makes it obvious that parts of the request will be kept private, but it does not explicitly state that the title and body will be published in two locations.

**Comment by zarino** [comment]
Designer notes:
* Users can supply 4 pieces of information: full name, email address, message subject, body.
* Two of these are *always* public (subject and body).
* One is *always* private (email address).
* One can be either public or private depending on the user ticking a box (full name).
* Idea: simplify the form by splitting it into two sections: "Public information – this will be displayed on this website and whatdotheyknow.com" (for the subject and body) and "Private information" (for the name and email) – then have the checkbox under the name field to let them "Make my name public".

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/foi-register/pull/271

![foi-reg](https://cloud.githubusercontent.com/assets/739624/8826424/5bbaf388-307e-11e5-8730-96ba848caddf.png)
