### ISSUE TITLE
scripts/provision.sh fails on last line

### ISSUE THREAD

**Issue by zarino** [mysociety/foi-register#265]
![screen shot 2015-07-21 at 16 00 12](https://cloud.githubusercontent.com/assets/739624/8804087/60d9ed7c-2fc2-11e5-8d81-b27bd5d3a9e2.png)

Running as part of `vagrant up`. I think it's this line causing the problem:

```
sudo chown -R vagrant:rvm /usr/local/rvm/
```

**Comment by dracos** [comment]
It's failing to install rvm before then (so that line then doesn't work), see the key verification failure.

**Comment by zarino** [comment]
Yep! That fixed it.

I've opened a new ticket for the fact that the Vagrantfile / provision.sh are out of date: https://github.com/mysociety/foi-register/issues/266
